on: 
    push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@master
     
      - name: Convert SVG
        uses: joergnapp/convert-svg-to-png@main
        with:
          svgpath: 'svg/'
          pngpath: 'png/'
          zoom: '16'

      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add png/*.png
          git commit -m "SVG to png" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: '${{ github.ref }}'
